### ISSUE TITLE
Please remove the 'And I output "[MTF - TESTCASE 5 - begin]"' steps in Behat

### ISSUE THREAD

**Issue by lucaboesch** [ethz-let/qtype_mtf#11]
Behat tests don't need that and it leads to a disturbing output.
Many thanks.

**Comment by Clyxz** [comment]
Hi Luca,
Thanks for your feedback. I understand the issue but this was a requirement for internal use.
The Behat tests are designed for internal use mainly since most of the test scenarios cover internal testcases and some steps like steps that are used for navigation require a specific page setup (theme).
However the Unittests are designed for generic use.
